/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as HomeRouteImport } from './pages/home'
import { Route as PhotoDetailsIdRouteImport } from './pages/photo-details.$id'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoDetailsIdRoute = PhotoDetailsIdRouteImport.update({
  id: '/photo-details/$id',
  path: '/photo-details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/photo-details/$id': typeof PhotoDetailsIdRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/photo-details/$id': typeof PhotoDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/photo-details/$id': typeof PhotoDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/photo-details/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/photo-details/$id'
  id: '__root__' | '/home' | '/photo-details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  PhotoDetailsIdRoute: typeof PhotoDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-details/$id': {
      id: '/photo-details/$id'
      path: '/photo-details/$id'
      fullPath: '/photo-details/$id'
      preLoaderRoute: typeof PhotoDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  PhotoDetailsIdRoute: PhotoDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
