/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as HomeIndexRouteImport } from './pages/home/index'
import { Route as PhotoDetailsPhotoIdRouteImport } from './pages/photo-details/$photoId'

const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoDetailsPhotoIdRoute = PhotoDetailsPhotoIdRouteImport.update({
  id: '/photo-details/$photoId',
  path: '/photo-details/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/photo-details/$photoId': typeof PhotoDetailsPhotoIdRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/photo-details/$photoId': typeof PhotoDetailsPhotoIdRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/photo-details/$photoId': typeof PhotoDetailsPhotoIdRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/photo-details/$photoId' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/photo-details/$photoId' | '/home'
  id: '__root__' | '/photo-details/$photoId' | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PhotoDetailsPhotoIdRoute: typeof PhotoDetailsPhotoIdRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-details/$photoId': {
      id: '/photo-details/$photoId'
      path: '/photo-details/$photoId'
      fullPath: '/photo-details/$photoId'
      preLoaderRoute: typeof PhotoDetailsPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PhotoDetailsPhotoIdRoute: PhotoDetailsPhotoIdRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
